### ISSUE TITLE
From Submission

### ISSUE THREAD

**Issue by eleopold** [MTUHIDE/ask-meagain#19]
Researching python end of submitting forms to the server, such as when they answer a question. Make sure to remember dealing with offline mode.

**Comment by joshuaha** [comment]
After briefly looking online, looks like this: https://www.tutorialspoint.com/flask/flask_sending_form_data_to_template.htm would be our best bet working with post form submissions for our project Instead of sending the result to another webpage we would just receive that data and store it in our database once we have that running. It would be nice to have a proof of concept going on this project, at least to show another page received the post data and then sent back to the landing page.
